<?php

use Illuminate\Database\Seeder;

class LanguageTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // google translate languages

        $languages = [
            ["name" => "Afrikaans"],
            ["name" => "Albanian"],
            ["name" => "Amharic"],
            ["name" => "Arabic"],
//            ["name" => "Armenian"],
            ["name" => "Azerbaijani"],
            ["name" => "Basque"],
            ["name" => "Belarusian"],
            ["name" => "Bengali"],
            ["name" => "Bosnian"],
            ["name" => "Bulgarian"],
            ["name" => "Burmese"],
            ["name" => "Catalan"],
            ["name" => "Cebuano"],
            ["name" => "Chichewa"],
            ["name" => "Chinese (Simplified)"],
            ["name" => "Chinese (Traditional)"],
            ["name" => "Corsican"],
            ["name" => "Croatian"],
            ["name" => "Czech"],
            ["name" => "Danish"],
            ["name" => "Dutch"],
            ["name" => "English"],
            ["name" => "Esperanto"],
            ["name" => "Estonian"],
            ["name" => "Filipino"],
            ["name" => "Finnish"],
            ["name" => "French"],
            ["name" => "Galician"],
            ["name" => "Georgian"],
            ["name" => "German"],
            ["name" => "Greek"],
            ["name" => "Gujarati"],
            ["name" => "Haitian Creole"],
            ["name" => "Hausa"],
            ["name" => "Hawaiian"],
            ["name" => "Hebrew"],
            ["name" => "Hindi"],
            ["name" => "Hmong"],
            ["name" => "Hungarian"],
            ["name" => "Icelandic"],
            ["name" => "Igbo"],
            ["name" => "Indonesian"],
            ["name" => "Irish"],
            ["name" => "Italian"],
            ["name" => "Japanese"],
            ["name" => "Javanese"],
            ["name" => "Kannada"],
            ["name" => "Kazakh"],
            ["name" => "Khmer"],
            ["name" => "Korean"],
            ["name" => "Kurdish (Kurmanji)"],
            ["name" => "Kyrgyz"],
            ["name" => "Lao"],
            ["name" => "Latin"],
            ["name" => "Latvian"],
            ["name" => "Lithuanian"],
            ["name" => "Luxembourgish"],
            ["name" => "Macedonian"],
            ["name" => "Malagasy"],
            ["name" => "Malay"],
            ["name" => "Malayalam"],
            ["name" => "Maltese"],
            ["name" => "Maori"],
            ["name" => "Marathi"],
            ["name" => "Mongolian"],
            ["name" => "Nepali"],
            ["name" => "Norwegian (Bokmål)"],
            ["name" => "Pashto"],
            ["name" => "Persian"],
            ["name" => "Polish"],
            ["name" => "Portuguese"],
            ["name" => "Punjabi"],
            ["name" => "Romanian"],
            ["name" => "Russian"],
            ["name" => "Samoan"],
            ["name" => "Scots Gaelic"],
            ["name" => "Serbian"],
            ["name" => "Sesotho"],
            ["name" => "Shona"],
            ["name" => "Sindhi"],
            ["name" => "Sinhala"],
            ["name" => "Slovak"],
            ["name" => "Slovenian"],
            ["name" => "Somali"],
            ["name" => "Spanish"],
            ["name" => "Sundanese"],
            ["name" => "Swahili"],
            ["name" => "Swedish"],
            ["name" => "Tajik"],
            ["name" => "Tamil"],
            ["name" => "Telugu"],
            ["name" => "Thai"],
            ["name" => "Turkish"],
            ["name" => "Ukrainian"],
            ["name" => "Urdu"],
            ["name" => "Uzbek"],
            ["name" => "Vietnamese"],
            ["name" => "Welsh"],
            ["name" => "West Frisian"],
            ["name" => "Xhosa"],
            ["name" => "Yiddish"],
            ["name" => "Yoruba"],
            ["name" => "Zulu"],
        ];

        DB::table('languages')->insert($languages);
    }
}
